/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as WhatZhcBuildsRouteImport } from './routes/what-zhc-builds'
import { Route as CybergrcIndexRouteImport } from './routes/cybergrc.index'
import { Route as CybergrcHowItWorksRouteImport } from './routes/cybergrc.how-it-works'
import { Route as CybergrcResourcesRouteImport } from './routes/cybergrc.resources'
import { Route as ExecutiveBriefingIndexRouteImport } from './routes/executive-briefing.index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsAgenticGovernanceRouteImport } from './routes/insights.agentic-governance'
import { Route as InsightsAutonomousSoftwareProductionRouteImport } from './routes/insights.autonomous-software-production'
import { Route as InsightsEnterpriseSovereigntyRouteImport } from './routes/insights.enterprise-sovereignty'
import { Route as InsightsExecutivePerspectivesRouteImport } from './routes/insights.executive-perspectives'
import { Route as OutcomesIndexRouteImport } from './routes/outcomes.index'
import { Route as OutcomesStorySlugRouteImport } from './routes/outcomes.$storySlug'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformAdoptRouteImport } from './routes/platform.adopt'
import { Route as PlatformHowItWorksRouteImport } from './routes/platform.how-it-works'
import { Route as PlatformMadamRouteImport } from './routes/platform.madam'
import { Route as TrustControlIndexRouteImport } from './routes/trust-control.index'
import { Route as TrustControlCodeOwnershipPortabilityRouteImport } from './routes/trust-control.code-ownership-portability'
import { Route as TrustControlDataHandlingResidencyRouteImport } from './routes/trust-control.data-handling-residency'
import { Route as TrustControlDeploymentArchitectureRouteImport } from './routes/trust-control.deployment-architecture'
import { Route as TrustControlSecurityArchitectureRouteImport } from './routes/trust-control.security-architecture'
import { Route as TrustControlSovereignDeploymentRouteImport } from './routes/trust-control.sovereign-deployment'
import { Route as CybergrcApplicationsIndexRouteImport } from './routes/cybergrc.applications.index'
import { Route as CybergrcApplicationsApplicationSlugRouteImport } from './routes/cybergrc.applications.$applicationSlug'
import { Route as CybergrcContactSalesIndexRouteImport } from './routes/cybergrc.contact-sales.index'
import { Route as TrustControlRequestSecurityOverviewIndexRouteImport } from './routes/trust-control.request-security-overview.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatZhcBuildsRoute = WhatZhcBuildsRouteImport.update({
  id: '/what-zhc-builds',
  path: '/what-zhc-builds',
  getParentRoute: () => rootRouteImport,
} as any)
const CybergrcIndexRoute = CybergrcIndexRouteImport.update({
  id: '/cybergrc/',
  path: '/cybergrc/',
  getParentRoute: () => rootRouteImport,
} as any)
const CybergrcHowItWorksRoute = CybergrcHowItWorksRouteImport.update({
  id: '/cybergrc/how-it-works',
  path: '/cybergrc/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CybergrcResourcesRoute = CybergrcResourcesRouteImport.update({
  id: '/cybergrc/resources',
  path: '/cybergrc/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveBriefingIndexRoute = ExecutiveBriefingIndexRouteImport.update({
  id: '/executive-briefing/',
  path: '/executive-briefing/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsAgenticGovernanceRoute =
  InsightsAgenticGovernanceRouteImport.update({
    id: '/insights/agentic-governance',
    path: '/insights/agentic-governance',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsAutonomousSoftwareProductionRoute =
  InsightsAutonomousSoftwareProductionRouteImport.update({
    id: '/insights/autonomous-software-production',
    path: '/insights/autonomous-software-production',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsEnterpriseSovereigntyRoute =
  InsightsEnterpriseSovereigntyRouteImport.update({
    id: '/insights/enterprise-sovereignty',
    path: '/insights/enterprise-sovereignty',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsExecutivePerspectivesRoute =
  InsightsExecutivePerspectivesRouteImport.update({
    id: '/insights/executive-perspectives',
    path: '/insights/executive-perspectives',
    getParentRoute: () => rootRouteImport,
  } as any)
const OutcomesIndexRoute = OutcomesIndexRouteImport.update({
  id: '/outcomes/',
  path: '/outcomes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesStorySlugRoute = OutcomesStorySlugRouteImport.update({
  id: '/outcomes/$storySlug',
  path: '/outcomes/$storySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdoptRoute = PlatformAdoptRouteImport.update({
  id: '/platform/adopt',
  path: '/platform/adopt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformHowItWorksRoute = PlatformHowItWorksRouteImport.update({
  id: '/platform/how-it-works',
  path: '/platform/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMadamRoute = PlatformMadamRouteImport.update({
  id: '/platform/madam',
  path: '/platform/madam',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustControlIndexRoute = TrustControlIndexRouteImport.update({
  id: '/trust-control/',
  path: '/trust-control/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustControlCodeOwnershipPortabilityRoute =
  TrustControlCodeOwnershipPortabilityRouteImport.update({
    id: '/trust-control/code-ownership-portability',
    path: '/trust-control/code-ownership-portability',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustControlDataHandlingResidencyRoute =
  TrustControlDataHandlingResidencyRouteImport.update({
    id: '/trust-control/data-handling-residency',
    path: '/trust-control/data-handling-residency',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustControlDeploymentArchitectureRoute =
  TrustControlDeploymentArchitectureRouteImport.update({
    id: '/trust-control/deployment-architecture',
    path: '/trust-control/deployment-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustControlSecurityArchitectureRoute =
  TrustControlSecurityArchitectureRouteImport.update({
    id: '/trust-control/security-architecture',
    path: '/trust-control/security-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustControlSovereignDeploymentRoute =
  TrustControlSovereignDeploymentRouteImport.update({
    id: '/trust-control/sovereign-deployment',
    path: '/trust-control/sovereign-deployment',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybergrcApplicationsIndexRoute =
  CybergrcApplicationsIndexRouteImport.update({
    id: '/cybergrc/applications/',
    path: '/cybergrc/applications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybergrcApplicationsApplicationSlugRoute =
  CybergrcApplicationsApplicationSlugRouteImport.update({
    id: '/cybergrc/applications/$applicationSlug',
    path: '/cybergrc/applications/$applicationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybergrcContactSalesIndexRoute =
  CybergrcContactSalesIndexRouteImport.update({
    id: '/cybergrc/contact-sales/',
    path: '/cybergrc/contact-sales/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustControlRequestSecurityOverviewIndexRoute =
  TrustControlRequestSecurityOverviewIndexRouteImport.update({
    id: '/trust-control/request-security-overview/',
    path: '/trust-control/request-security-overview/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/what-zhc-builds': typeof WhatZhcBuildsRoute
  '/cybergrc/how-it-works': typeof CybergrcHowItWorksRoute
  '/cybergrc/resources': typeof CybergrcResourcesRoute
  '/insights/agentic-governance': typeof InsightsAgenticGovernanceRoute
  '/insights/autonomous-software-production': typeof InsightsAutonomousSoftwareProductionRoute
  '/insights/enterprise-sovereignty': typeof InsightsEnterpriseSovereigntyRoute
  '/insights/executive-perspectives': typeof InsightsExecutivePerspectivesRoute
  '/outcomes/$storySlug': typeof OutcomesStorySlugRoute
  '/platform/adopt': typeof PlatformAdoptRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/madam': typeof PlatformMadamRoute
  '/trust-control/code-ownership-portability': typeof TrustControlCodeOwnershipPortabilityRoute
  '/trust-control/data-handling-residency': typeof TrustControlDataHandlingResidencyRoute
  '/trust-control/deployment-architecture': typeof TrustControlDeploymentArchitectureRoute
  '/trust-control/security-architecture': typeof TrustControlSecurityArchitectureRoute
  '/trust-control/sovereign-deployment': typeof TrustControlSovereignDeploymentRoute
  '/cybergrc/': typeof CybergrcIndexRoute
  '/executive-briefing/': typeof ExecutiveBriefingIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trust-control/': typeof TrustControlIndexRoute
  '/cybergrc/applications/$applicationSlug': typeof CybergrcApplicationsApplicationSlugRoute
  '/cybergrc/applications/': typeof CybergrcApplicationsIndexRoute
  '/cybergrc/contact-sales/': typeof CybergrcContactSalesIndexRoute
  '/trust-control/request-security-overview/': typeof TrustControlRequestSecurityOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/what-zhc-builds': typeof WhatZhcBuildsRoute
  '/cybergrc/how-it-works': typeof CybergrcHowItWorksRoute
  '/cybergrc/resources': typeof CybergrcResourcesRoute
  '/insights/agentic-governance': typeof InsightsAgenticGovernanceRoute
  '/insights/autonomous-software-production': typeof InsightsAutonomousSoftwareProductionRoute
  '/insights/enterprise-sovereignty': typeof InsightsEnterpriseSovereigntyRoute
  '/insights/executive-perspectives': typeof InsightsExecutivePerspectivesRoute
  '/outcomes/$storySlug': typeof OutcomesStorySlugRoute
  '/platform/adopt': typeof PlatformAdoptRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/madam': typeof PlatformMadamRoute
  '/trust-control/code-ownership-portability': typeof TrustControlCodeOwnershipPortabilityRoute
  '/trust-control/data-handling-residency': typeof TrustControlDataHandlingResidencyRoute
  '/trust-control/deployment-architecture': typeof TrustControlDeploymentArchitectureRoute
  '/trust-control/security-architecture': typeof TrustControlSecurityArchitectureRoute
  '/trust-control/sovereign-deployment': typeof TrustControlSovereignDeploymentRoute
  '/cybergrc': typeof CybergrcIndexRoute
  '/executive-briefing': typeof ExecutiveBriefingIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/outcomes': typeof OutcomesIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/trust-control': typeof TrustControlIndexRoute
  '/cybergrc/applications/$applicationSlug': typeof CybergrcApplicationsApplicationSlugRoute
  '/cybergrc/applications': typeof CybergrcApplicationsIndexRoute
  '/cybergrc/contact-sales': typeof CybergrcContactSalesIndexRoute
  '/trust-control/request-security-overview': typeof TrustControlRequestSecurityOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/what-zhc-builds': typeof WhatZhcBuildsRoute
  '/cybergrc/how-it-works': typeof CybergrcHowItWorksRoute
  '/cybergrc/resources': typeof CybergrcResourcesRoute
  '/insights/agentic-governance': typeof InsightsAgenticGovernanceRoute
  '/insights/autonomous-software-production': typeof InsightsAutonomousSoftwareProductionRoute
  '/insights/enterprise-sovereignty': typeof InsightsEnterpriseSovereigntyRoute
  '/insights/executive-perspectives': typeof InsightsExecutivePerspectivesRoute
  '/outcomes/$storySlug': typeof OutcomesStorySlugRoute
  '/platform/adopt': typeof PlatformAdoptRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/madam': typeof PlatformMadamRoute
  '/trust-control/code-ownership-portability': typeof TrustControlCodeOwnershipPortabilityRoute
  '/trust-control/data-handling-residency': typeof TrustControlDataHandlingResidencyRoute
  '/trust-control/deployment-architecture': typeof TrustControlDeploymentArchitectureRoute
  '/trust-control/security-architecture': typeof TrustControlSecurityArchitectureRoute
  '/trust-control/sovereign-deployment': typeof TrustControlSovereignDeploymentRoute
  '/cybergrc/': typeof CybergrcIndexRoute
  '/executive-briefing/': typeof ExecutiveBriefingIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trust-control/': typeof TrustControlIndexRoute
  '/cybergrc/applications/$applicationSlug': typeof CybergrcApplicationsApplicationSlugRoute
  '/cybergrc/applications/': typeof CybergrcApplicationsIndexRoute
  '/cybergrc/contact-sales/': typeof CybergrcContactSalesIndexRoute
  '/trust-control/request-security-overview/': typeof TrustControlRequestSecurityOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/what-zhc-builds'
    | '/cybergrc/how-it-works'
    | '/cybergrc/resources'
    | '/insights/agentic-governance'
    | '/insights/autonomous-software-production'
    | '/insights/enterprise-sovereignty'
    | '/insights/executive-perspectives'
    | '/outcomes/$storySlug'
    | '/platform/adopt'
    | '/platform/how-it-works'
    | '/platform/madam'
    | '/trust-control/code-ownership-portability'
    | '/trust-control/data-handling-residency'
    | '/trust-control/deployment-architecture'
    | '/trust-control/security-architecture'
    | '/trust-control/sovereign-deployment'
    | '/cybergrc/'
    | '/executive-briefing/'
    | '/insights/'
    | '/outcomes/'
    | '/platform/'
    | '/trust-control/'
    | '/cybergrc/applications/$applicationSlug'
    | '/cybergrc/applications/'
    | '/cybergrc/contact-sales/'
    | '/trust-control/request-security-overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/what-zhc-builds'
    | '/cybergrc/how-it-works'
    | '/cybergrc/resources'
    | '/insights/agentic-governance'
    | '/insights/autonomous-software-production'
    | '/insights/enterprise-sovereignty'
    | '/insights/executive-perspectives'
    | '/outcomes/$storySlug'
    | '/platform/adopt'
    | '/platform/how-it-works'
    | '/platform/madam'
    | '/trust-control/code-ownership-portability'
    | '/trust-control/data-handling-residency'
    | '/trust-control/deployment-architecture'
    | '/trust-control/security-architecture'
    | '/trust-control/sovereign-deployment'
    | '/cybergrc'
    | '/executive-briefing'
    | '/insights'
    | '/outcomes'
    | '/platform'
    | '/trust-control'
    | '/cybergrc/applications/$applicationSlug'
    | '/cybergrc/applications'
    | '/cybergrc/contact-sales'
    | '/trust-control/request-security-overview'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/what-zhc-builds'
    | '/cybergrc/how-it-works'
    | '/cybergrc/resources'
    | '/insights/agentic-governance'
    | '/insights/autonomous-software-production'
    | '/insights/enterprise-sovereignty'
    | '/insights/executive-perspectives'
    | '/outcomes/$storySlug'
    | '/platform/adopt'
    | '/platform/how-it-works'
    | '/platform/madam'
    | '/trust-control/code-ownership-portability'
    | '/trust-control/data-handling-residency'
    | '/trust-control/deployment-architecture'
    | '/trust-control/security-architecture'
    | '/trust-control/sovereign-deployment'
    | '/cybergrc/'
    | '/executive-briefing/'
    | '/insights/'
    | '/outcomes/'
    | '/platform/'
    | '/trust-control/'
    | '/cybergrc/applications/$applicationSlug'
    | '/cybergrc/applications/'
    | '/cybergrc/contact-sales/'
    | '/trust-control/request-security-overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  WhatZhcBuildsRoute: typeof WhatZhcBuildsRoute
  CybergrcHowItWorksRoute: typeof CybergrcHowItWorksRoute
  CybergrcResourcesRoute: typeof CybergrcResourcesRoute
  InsightsAgenticGovernanceRoute: typeof InsightsAgenticGovernanceRoute
  InsightsAutonomousSoftwareProductionRoute: typeof InsightsAutonomousSoftwareProductionRoute
  InsightsEnterpriseSovereigntyRoute: typeof InsightsEnterpriseSovereigntyRoute
  InsightsExecutivePerspectivesRoute: typeof InsightsExecutivePerspectivesRoute
  OutcomesStorySlugRoute: typeof OutcomesStorySlugRoute
  PlatformAdoptRoute: typeof PlatformAdoptRoute
  PlatformHowItWorksRoute: typeof PlatformHowItWorksRoute
  PlatformMadamRoute: typeof PlatformMadamRoute
  TrustControlCodeOwnershipPortabilityRoute: typeof TrustControlCodeOwnershipPortabilityRoute
  TrustControlDataHandlingResidencyRoute: typeof TrustControlDataHandlingResidencyRoute
  TrustControlDeploymentArchitectureRoute: typeof TrustControlDeploymentArchitectureRoute
  TrustControlSecurityArchitectureRoute: typeof TrustControlSecurityArchitectureRoute
  TrustControlSovereignDeploymentRoute: typeof TrustControlSovereignDeploymentRoute
  CybergrcIndexRoute: typeof CybergrcIndexRoute
  ExecutiveBriefingIndexRoute: typeof ExecutiveBriefingIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  OutcomesIndexRoute: typeof OutcomesIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  TrustControlIndexRoute: typeof TrustControlIndexRoute
  CybergrcApplicationsApplicationSlugRoute: typeof CybergrcApplicationsApplicationSlugRoute
  CybergrcApplicationsIndexRoute: typeof CybergrcApplicationsIndexRoute
  CybergrcContactSalesIndexRoute: typeof CybergrcContactSalesIndexRoute
  TrustControlRequestSecurityOverviewIndexRoute: typeof TrustControlRequestSecurityOverviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-zhc-builds': {
      id: '/what-zhc-builds'
      path: '/what-zhc-builds'
      fullPath: '/what-zhc-builds'
      preLoaderRoute: typeof WhatZhcBuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybergrc/': {
      id: '/cybergrc/'
      path: '/cybergrc'
      fullPath: '/cybergrc/'
      preLoaderRoute: typeof CybergrcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybergrc/how-it-works': {
      id: '/cybergrc/how-it-works'
      path: '/cybergrc/how-it-works'
      fullPath: '/cybergrc/how-it-works'
      preLoaderRoute: typeof CybergrcHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybergrc/resources': {
      id: '/cybergrc/resources'
      path: '/cybergrc/resources'
      fullPath: '/cybergrc/resources'
      preLoaderRoute: typeof CybergrcResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-briefing/': {
      id: '/executive-briefing/'
      path: '/executive-briefing'
      fullPath: '/executive-briefing/'
      preLoaderRoute: typeof ExecutiveBriefingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/agentic-governance': {
      id: '/insights/agentic-governance'
      path: '/insights/agentic-governance'
      fullPath: '/insights/agentic-governance'
      preLoaderRoute: typeof InsightsAgenticGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/autonomous-software-production': {
      id: '/insights/autonomous-software-production'
      path: '/insights/autonomous-software-production'
      fullPath: '/insights/autonomous-software-production'
      preLoaderRoute: typeof InsightsAutonomousSoftwareProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/enterprise-sovereignty': {
      id: '/insights/enterprise-sovereignty'
      path: '/insights/enterprise-sovereignty'
      fullPath: '/insights/enterprise-sovereignty'
      preLoaderRoute: typeof InsightsEnterpriseSovereigntyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/executive-perspectives': {
      id: '/insights/executive-perspectives'
      path: '/insights/executive-perspectives'
      fullPath: '/insights/executive-perspectives'
      preLoaderRoute: typeof InsightsExecutivePerspectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/': {
      id: '/outcomes/'
      path: '/outcomes'
      fullPath: '/outcomes/'
      preLoaderRoute: typeof OutcomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/$storySlug': {
      id: '/outcomes/$storySlug'
      path: '/outcomes/$storySlug'
      fullPath: '/outcomes/$storySlug'
      preLoaderRoute: typeof OutcomesStorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/adopt': {
      id: '/platform/adopt'
      path: '/platform/adopt'
      fullPath: '/platform/adopt'
      preLoaderRoute: typeof PlatformAdoptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/how-it-works': {
      id: '/platform/how-it-works'
      path: '/platform/how-it-works'
      fullPath: '/platform/how-it-works'
      preLoaderRoute: typeof PlatformHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/madam': {
      id: '/platform/madam'
      path: '/platform/madam'
      fullPath: '/platform/madam'
      preLoaderRoute: typeof PlatformMadamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/': {
      id: '/trust-control/'
      path: '/trust-control'
      fullPath: '/trust-control/'
      preLoaderRoute: typeof TrustControlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/code-ownership-portability': {
      id: '/trust-control/code-ownership-portability'
      path: '/trust-control/code-ownership-portability'
      fullPath: '/trust-control/code-ownership-portability'
      preLoaderRoute: typeof TrustControlCodeOwnershipPortabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/data-handling-residency': {
      id: '/trust-control/data-handling-residency'
      path: '/trust-control/data-handling-residency'
      fullPath: '/trust-control/data-handling-residency'
      preLoaderRoute: typeof TrustControlDataHandlingResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/deployment-architecture': {
      id: '/trust-control/deployment-architecture'
      path: '/trust-control/deployment-architecture'
      fullPath: '/trust-control/deployment-architecture'
      preLoaderRoute: typeof TrustControlDeploymentArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/security-architecture': {
      id: '/trust-control/security-architecture'
      path: '/trust-control/security-architecture'
      fullPath: '/trust-control/security-architecture'
      preLoaderRoute: typeof TrustControlSecurityArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/sovereign-deployment': {
      id: '/trust-control/sovereign-deployment'
      path: '/trust-control/sovereign-deployment'
      fullPath: '/trust-control/sovereign-deployment'
      preLoaderRoute: typeof TrustControlSovereignDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybergrc/applications/': {
      id: '/cybergrc/applications/'
      path: '/cybergrc/applications'
      fullPath: '/cybergrc/applications/'
      preLoaderRoute: typeof CybergrcApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybergrc/applications/$applicationSlug': {
      id: '/cybergrc/applications/$applicationSlug'
      path: '/cybergrc/applications/$applicationSlug'
      fullPath: '/cybergrc/applications/$applicationSlug'
      preLoaderRoute: typeof CybergrcApplicationsApplicationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybergrc/contact-sales/': {
      id: '/cybergrc/contact-sales/'
      path: '/cybergrc/contact-sales'
      fullPath: '/cybergrc/contact-sales/'
      preLoaderRoute: typeof CybergrcContactSalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-control/request-security-overview/': {
      id: '/trust-control/request-security-overview/'
      path: '/trust-control/request-security-overview'
      fullPath: '/trust-control/request-security-overview/'
      preLoaderRoute: typeof TrustControlRequestSecurityOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  WhatZhcBuildsRoute: WhatZhcBuildsRoute,
  CybergrcHowItWorksRoute: CybergrcHowItWorksRoute,
  CybergrcResourcesRoute: CybergrcResourcesRoute,
  InsightsAgenticGovernanceRoute: InsightsAgenticGovernanceRoute,
  InsightsAutonomousSoftwareProductionRoute:
    InsightsAutonomousSoftwareProductionRoute,
  InsightsEnterpriseSovereigntyRoute: InsightsEnterpriseSovereigntyRoute,
  InsightsExecutivePerspectivesRoute: InsightsExecutivePerspectivesRoute,
  OutcomesStorySlugRoute: OutcomesStorySlugRoute,
  PlatformAdoptRoute: PlatformAdoptRoute,
  PlatformHowItWorksRoute: PlatformHowItWorksRoute,
  PlatformMadamRoute: PlatformMadamRoute,
  TrustControlCodeOwnershipPortabilityRoute:
    TrustControlCodeOwnershipPortabilityRoute,
  TrustControlDataHandlingResidencyRoute:
    TrustControlDataHandlingResidencyRoute,
  TrustControlDeploymentArchitectureRoute:
    TrustControlDeploymentArchitectureRoute,
  TrustControlSecurityArchitectureRoute: TrustControlSecurityArchitectureRoute,
  TrustControlSovereignDeploymentRoute: TrustControlSovereignDeploymentRoute,
  CybergrcIndexRoute: CybergrcIndexRoute,
  ExecutiveBriefingIndexRoute: ExecutiveBriefingIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  OutcomesIndexRoute: OutcomesIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  TrustControlIndexRoute: TrustControlIndexRoute,
  CybergrcApplicationsApplicationSlugRoute:
    CybergrcApplicationsApplicationSlugRoute,
  CybergrcApplicationsIndexRoute: CybergrcApplicationsIndexRoute,
  CybergrcContactSalesIndexRoute: CybergrcContactSalesIndexRoute,
  TrustControlRequestSecurityOverviewIndexRoute:
    TrustControlRequestSecurityOverviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
