/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatWeBuildRouteImport } from './routes/what-we-build'
import { Route as OutcomesIndexRouteImport } from './routes/outcomes.index'
import { Route as OutcomesStorySlugRouteImport } from './routes/outcomes.$storySlug'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformAdoptRouteImport } from './routes/platform.adopt'
import { Route as PlatformHowItWorksRouteImport } from './routes/platform.how-it-works'
import { Route as PlatformMadamRouteImport } from './routes/platform.madam'
import { Route as TrustIndexRouteImport } from './routes/trust.index'
import { Route as TrustCodeOwnershipRouteImport } from './routes/trust.code-ownership'
import { Route as TrustDataResidencyRouteImport } from './routes/trust.data-residency'
import { Route as TrustDeploymentArchitectureRouteImport } from './routes/trust.deployment-architecture'
import { Route as TrustSecurityArchitectureRouteImport } from './routes/trust.security-architecture'
import { Route as TrustSecurityOverviewRouteImport } from './routes/trust.security-overview'
import { Route as TrustSovereignDeploymentRouteImport } from './routes/trust.sovereign-deployment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeBuildRoute = WhatWeBuildRouteImport.update({
  id: '/what-we-build',
  path: '/what-we-build',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesIndexRoute = OutcomesIndexRouteImport.update({
  id: '/outcomes/',
  path: '/outcomes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomesStorySlugRoute = OutcomesStorySlugRouteImport.update({
  id: '/outcomes/$storySlug',
  path: '/outcomes/$storySlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdoptRoute = PlatformAdoptRouteImport.update({
  id: '/platform/adopt',
  path: '/platform/adopt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformHowItWorksRoute = PlatformHowItWorksRouteImport.update({
  id: '/platform/how-it-works',
  path: '/platform/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMadamRoute = PlatformMadamRouteImport.update({
  id: '/platform/madam',
  path: '/platform/madam',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustIndexRoute = TrustIndexRouteImport.update({
  id: '/trust/',
  path: '/trust/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCodeOwnershipRoute = TrustCodeOwnershipRouteImport.update({
  id: '/trust/code-ownership',
  path: '/trust/code-ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustDataResidencyRoute = TrustDataResidencyRouteImport.update({
  id: '/trust/data-residency',
  path: '/trust/data-residency',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustDeploymentArchitectureRoute =
  TrustDeploymentArchitectureRouteImport.update({
    id: '/trust/deployment-architecture',
    path: '/trust/deployment-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustSecurityArchitectureRoute =
  TrustSecurityArchitectureRouteImport.update({
    id: '/trust/security-architecture',
    path: '/trust/security-architecture',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrustSecurityOverviewRoute = TrustSecurityOverviewRouteImport.update({
  id: '/trust/security-overview',
  path: '/trust/security-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustSovereignDeploymentRoute =
  TrustSovereignDeploymentRouteImport.update({
    id: '/trust/sovereign-deployment',
    path: '/trust/sovereign-deployment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/outcomes/$storySlug': typeof OutcomesStorySlugRoute
  '/platform/adopt': typeof PlatformAdoptRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/madam': typeof PlatformMadamRoute
  '/trust/code-ownership': typeof TrustCodeOwnershipRoute
  '/trust/data-residency': typeof TrustDataResidencyRoute
  '/trust/deployment-architecture': typeof TrustDeploymentArchitectureRoute
  '/trust/security-architecture': typeof TrustSecurityArchitectureRoute
  '/trust/security-overview': typeof TrustSecurityOverviewRoute
  '/trust/sovereign-deployment': typeof TrustSovereignDeploymentRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trust/': typeof TrustIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/outcomes/$storySlug': typeof OutcomesStorySlugRoute
  '/platform/adopt': typeof PlatformAdoptRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/madam': typeof PlatformMadamRoute
  '/trust/code-ownership': typeof TrustCodeOwnershipRoute
  '/trust/data-residency': typeof TrustDataResidencyRoute
  '/trust/deployment-architecture': typeof TrustDeploymentArchitectureRoute
  '/trust/security-architecture': typeof TrustSecurityArchitectureRoute
  '/trust/security-overview': typeof TrustSecurityOverviewRoute
  '/trust/sovereign-deployment': typeof TrustSovereignDeploymentRoute
  '/outcomes': typeof OutcomesIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/trust': typeof TrustIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/what-we-build': typeof WhatWeBuildRoute
  '/outcomes/$storySlug': typeof OutcomesStorySlugRoute
  '/platform/adopt': typeof PlatformAdoptRoute
  '/platform/how-it-works': typeof PlatformHowItWorksRoute
  '/platform/madam': typeof PlatformMadamRoute
  '/trust/code-ownership': typeof TrustCodeOwnershipRoute
  '/trust/data-residency': typeof TrustDataResidencyRoute
  '/trust/deployment-architecture': typeof TrustDeploymentArchitectureRoute
  '/trust/security-architecture': typeof TrustSecurityArchitectureRoute
  '/trust/security-overview': typeof TrustSecurityOverviewRoute
  '/trust/sovereign-deployment': typeof TrustSovereignDeploymentRoute
  '/outcomes/': typeof OutcomesIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/trust/': typeof TrustIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/what-we-build'
    | '/outcomes/$storySlug'
    | '/platform/adopt'
    | '/platform/how-it-works'
    | '/platform/madam'
    | '/trust/code-ownership'
    | '/trust/data-residency'
    | '/trust/deployment-architecture'
    | '/trust/security-architecture'
    | '/trust/security-overview'
    | '/trust/sovereign-deployment'
    | '/outcomes/'
    | '/platform/'
    | '/trust/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/what-we-build'
    | '/outcomes/$storySlug'
    | '/platform/adopt'
    | '/platform/how-it-works'
    | '/platform/madam'
    | '/trust/code-ownership'
    | '/trust/data-residency'
    | '/trust/deployment-architecture'
    | '/trust/security-architecture'
    | '/trust/security-overview'
    | '/trust/sovereign-deployment'
    | '/outcomes'
    | '/platform'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/what-we-build'
    | '/outcomes/$storySlug'
    | '/platform/adopt'
    | '/platform/how-it-works'
    | '/platform/madam'
    | '/trust/code-ownership'
    | '/trust/data-residency'
    | '/trust/deployment-architecture'
    | '/trust/security-architecture'
    | '/trust/security-overview'
    | '/trust/sovereign-deployment'
    | '/outcomes/'
    | '/platform/'
    | '/trust/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WhatWeBuildRoute: typeof WhatWeBuildRoute
  OutcomesStorySlugRoute: typeof OutcomesStorySlugRoute
  PlatformAdoptRoute: typeof PlatformAdoptRoute
  PlatformHowItWorksRoute: typeof PlatformHowItWorksRoute
  PlatformMadamRoute: typeof PlatformMadamRoute
  TrustCodeOwnershipRoute: typeof TrustCodeOwnershipRoute
  TrustDataResidencyRoute: typeof TrustDataResidencyRoute
  TrustDeploymentArchitectureRoute: typeof TrustDeploymentArchitectureRoute
  TrustSecurityArchitectureRoute: typeof TrustSecurityArchitectureRoute
  TrustSecurityOverviewRoute: typeof TrustSecurityOverviewRoute
  TrustSovereignDeploymentRoute: typeof TrustSovereignDeploymentRoute
  OutcomesIndexRoute: typeof OutcomesIndexRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  TrustIndexRoute: typeof TrustIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-build': {
      id: '/what-we-build'
      path: '/what-we-build'
      fullPath: '/what-we-build'
      preLoaderRoute: typeof WhatWeBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/': {
      id: '/outcomes/'
      path: '/outcomes'
      fullPath: '/outcomes/'
      preLoaderRoute: typeof OutcomesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcomes/$storySlug': {
      id: '/outcomes/$storySlug'
      path: '/outcomes/$storySlug'
      fullPath: '/outcomes/$storySlug'
      preLoaderRoute: typeof OutcomesStorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/adopt': {
      id: '/platform/adopt'
      path: '/platform/adopt'
      fullPath: '/platform/adopt'
      preLoaderRoute: typeof PlatformAdoptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/how-it-works': {
      id: '/platform/how-it-works'
      path: '/platform/how-it-works'
      fullPath: '/platform/how-it-works'
      preLoaderRoute: typeof PlatformHowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/madam': {
      id: '/platform/madam'
      path: '/platform/madam'
      fullPath: '/platform/madam'
      preLoaderRoute: typeof PlatformMadamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/': {
      id: '/trust/'
      path: '/trust'
      fullPath: '/trust/'
      preLoaderRoute: typeof TrustIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/code-ownership': {
      id: '/trust/code-ownership'
      path: '/trust/code-ownership'
      fullPath: '/trust/code-ownership'
      preLoaderRoute: typeof TrustCodeOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/data-residency': {
      id: '/trust/data-residency'
      path: '/trust/data-residency'
      fullPath: '/trust/data-residency'
      preLoaderRoute: typeof TrustDataResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/deployment-architecture': {
      id: '/trust/deployment-architecture'
      path: '/trust/deployment-architecture'
      fullPath: '/trust/deployment-architecture'
      preLoaderRoute: typeof TrustDeploymentArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/security-architecture': {
      id: '/trust/security-architecture'
      path: '/trust/security-architecture'
      fullPath: '/trust/security-architecture'
      preLoaderRoute: typeof TrustSecurityArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/security-overview': {
      id: '/trust/security-overview'
      path: '/trust/security-overview'
      fullPath: '/trust/security-overview'
      preLoaderRoute: typeof TrustSecurityOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust/sovereign-deployment': {
      id: '/trust/sovereign-deployment'
      path: '/trust/sovereign-deployment'
      fullPath: '/trust/sovereign-deployment'
      preLoaderRoute: typeof TrustSovereignDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WhatWeBuildRoute: WhatWeBuildRoute,
  OutcomesStorySlugRoute: OutcomesStorySlugRoute,
  PlatformAdoptRoute: PlatformAdoptRoute,
  PlatformHowItWorksRoute: PlatformHowItWorksRoute,
  PlatformMadamRoute: PlatformMadamRoute,
  TrustCodeOwnershipRoute: TrustCodeOwnershipRoute,
  TrustDataResidencyRoute: TrustDataResidencyRoute,
  TrustDeploymentArchitectureRoute: TrustDeploymentArchitectureRoute,
  TrustSecurityArchitectureRoute: TrustSecurityArchitectureRoute,
  TrustSecurityOverviewRoute: TrustSecurityOverviewRoute,
  TrustSovereignDeploymentRoute: TrustSovereignDeploymentRoute,
  OutcomesIndexRoute: OutcomesIndexRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  TrustIndexRoute: TrustIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
